version: '3'

services:
  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    restart: always

  fastcgi_app:
    build: ./fastcgi
    ports:
       - "9000"
    restart: always
