version: '3.8'

services:
  wildfly:
    build: .
    ports:
      - "80:8080"

  postgres:
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    build: ./db
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
